app/auth.py

This has already been fixed in the `main` branch. However, while folks are still working in `39-blogposts`, it would be nice if the logout function worked.

updated reference to `main.index` to fix `logout()`

---

app/routes.py
app/static/main.css
app/templates/blog/blog.html
app/templates/edit_profile.html
app/templates/login.html
app/templates/profile/profile.html
app/templates/signup.html

You can edit your profile by clicking the "Edit Profile" button to toggle a form to change name and email. You can press the "Cancel" button toggle off the form and view your current profile information. After changing information, press the "Save" button to submit and the name and email will be updated in the database and will reload the profile page and display the updated information.

37 profile page edit

---

app/templates/right_window/profile_info.html

I only removed the password from the link list on the right_window\profile_info.html

removed the password link from the list

---

app/routes.py
app/templates/edit_profile.html
app/templates/layout.html
app/templates/profile/profile.html

Edit password with error handling when current password is incorrect, or when new password and new confirmation password don't match.

75 edit passwords needs to function andy

---

.gitignore
app/models.py

Added the Forum_Comment model to models.py, with what I hope to be the right classifications, and correct link between Forum_Post and Forum_Comment.

Forum comment data model

---

app/company_info.py

added the company id and current_user.id to company membership table when creating a company

company membership table

---

app/profiles.py
app/routes.py
app/templates/company_info/company_info.html
app/templates/company_info/company_info_create.html
app/templates/company_info/company_info_main.html

* unfinished base for company info page
* placeholders
* added company info routes
* added form values based on company model names
* fixed edit info bug
* small style comment
* added table variables
* retrieve information from form to routes.py
* restructure company page template
* removed company info routes
* made company info routes file based on blogposts
* added create company feature
* adjustments to inputs
* added asterisk to required fields
* took out values
* create company button
* Update company_info.py
* Update company_info.html
* PR changes (states, profile routes)
* company membership table
added the company id and current_user.id to company membership table when creating a company
* update edit company info
* update edit company info
* added updates to company_info.py to …

79 company info page

---

.gitignore
app/models.py
app/routes.py
app/static/main.css
app/templates/forums.html

I created a create forum post form. The form is only viewable if you are signed in. 
I also added an `id` url variable in the forums route. Based on the forum `id`, the form includes it as a hidden input, so the backend knows which forum to create the post in. The route /forums  with no `id`, also now routes to a default forum which is currently `id=1`.

85 create forum post form andy

---

app/models.py

I have added the Ticket Comment ORM table.

Ticket Comment ORM

---

app/models.py

I have made a typo mistake in Ticket Table. Thus created a new pull request.

114 customer system js

---

app/models.py

I have created tables but was unable to use inheritance.

Ticket Forum ORM

---

app/__init__.py
app/forums.py
app/models.py
app/routes.py

completed post delete and forum post model. Error check for missing post needs to be handled

97 90 delete feature kg

---

app/routes/forums.py
app/static/main.css
app/templates/forums/alternating_color_table.html
app/templates/forums/create_post.html
app/templates/forums/create_thread.html
app/templates/forums/post.html
app/templates/forums/thread.html
app/templates/forums/threads.html

Create/delete functionality added for threads, posts, comments. No role based access to create/delete functionality yet added.

Dev james forum forms

---

.gitignore
Dockerfile
app/__init__.py
app/routes/__init__.py
app/templates/products/products.html
run.py
uwsgi.ini

I am cutting this PR for @loknara

208 blueprint consolidate

---

app/__init__.py
app/admin/__init__.py
app/admin/views.py
app/db/__init__.py
app/db/models/__init__.py
app/db/models/blog.py
app/db/models/customer.py
app/db/models/ticket.py
app/routes/__init__.py
app/routes/auth.py
app/routes/blogPosts.py
app/routes/calendar.py
app/routes/companies.py
app/routes/forums.py
app/routes/main.py
app/routes/profiles.py
app/routes/tickets.py
app/util/log/config.py
app/util/security/__init__.py
app/util/webhooks/__init__.py
seeder.py

enforce pep8 to all imports in .py files

---

andrew-seed.py
app/db/models/calendar.py
app/db/models/customer.py
app/routes/calendar.py
app/templates/calendar/calendar.html
app/templates/calendar/create_event.html
app/templates/calendar/event.html
seeder.py

Please use my seeder file for easy testing since we only need a subset of seeder.py, and this subset is directly related to these tickets.

fix tickets 221, 222, 223, 224

---

andrew-seed.py
app/db/models/calendar.py
app/db/models/customer.py
app/routes/calendar.py
app/templates/calendar/calendar.html
app/templates/calendar/create_event.html
app/templates/calendar/event.html
seeder.py

* fix tickets 221, 222, 223, 224
* added updated seeder.py
Co-authored-by: Loc Pham <loc.pham@advocado.me>
Co-authored-by: stuart <stuart@tobupengin.com>

fix tickets 221, 222, 223, 224 (#236)

---

app/routes/__init__.py
app/routes/about.py
app/routes/home.py
app/routes/products.py
app/templates/about/about_main.html
app/templates/home/home.html
app/util/s3/config.py

234 task add s3 get url function to views

---

app/routes/companies.py
app/templates/company_info/company_info_main.html

locked up companies

---

app/static/main.css
app/templates/about/about_main.html
app/templates/home/home.html

Solution for fixing bug 263 can fix bug 264 too. I didn't create a separate PR for 264, but if the home and about styling works as expected, then you can close both 263 and 264 tickets.

263 fix styling bug in about page

---

app/routes/forums.py
app/templates/forums/create_thread.html
app/templates/forums/threads.html
manage.py

Updated all of the tickets as instructed.

Closes 261 Closes 284 Closes 285 Closes 286 Closes 287

---

app/static/main.css
app/templates/home/home.html

Co-authored-by: Loc Pham <loc.pham@advocado.me>

fix ticket 264 (#282) Closes 264

---

app/static/main.css
app/templates/blog/blog.html
app/templates/blog/blog_main.html

* delete unused folder
* create init file
* create init file
* move routes into folder
* edit formatting. remove comments
* move db initialization to models
* move admin initialization to admin.py
* fix imports
* remove comment
* remove comments edit formatting
* fix variable name
* edit formatting
* edit formatting
* edit formatting
* Edit formatting
* edit formatting
* fix import
* fix import
* fix whitespace
* remove comments
* add venv folder to gitignore
* Add forum post and forum comment models
* Split forums route into new file
* fix imports
* add line
* remove comment
* move forum template to new folder
* add db query
* create seeder script
* remove unique constraint on date
* remove unique constraints
* remove unique constraint
* fix errors
* create template files
* Fix routes …

fix minor quirks in blog page (#283)

---

app/static/main.css

Co-authored-by: Loc Pham <loc.pham@advocado.me>
Closes 267

apply common theme to calendar event page (#308)

---

app/static/main.css
app/templates/about/about_main.html
app/templates/home/home.html

Co-authored-by: Loc Pham <loc.pham@advocado.me>
Closes 299

299: make white texts in blue container in about/home page (#309)

---

app/db/util.py
app/routes/blog_posts.py
app/routes/calendar.py
app/routes/forums.py
app/routes/products.py
app/routes/tickets.py
app/static/main.css
app/templates/blog/link_list.html
app/templates/calendar/calendar.html
app/templates/forums/threads.html
app/templates/macros/paginate.html
app/templates/products/products.html
app/templates/tickets/ticket_list.html

1. Apply util paginate() function to all pages that has displaying of items
2. Add extra customizations to paginate()
3. Fix styling for pagination-list

315: paginate api

---

app/__init__.py
app/admin/__init__.py
app/db/models/__init__.py
app/db/models/orders.py
app/routes/__init__.py
app/routes/orders.py
app/static/javascript/scripts.js
app/static/main.css
app/templates/order_info/order_info.html
app/templates/order_info/order_info_create.html
app/templates/order_info/order_info_edit.html
app/templates/order_info/order_info_main.html
app/templates/right_window/profile_info.html

manually type /orders/create to get to the page

337 feature order editor james

---

app/__init__.py
app/admin/__init__.py
app/db/models/__init__.py
app/db/models/orders.py
app/routes/__init__.py
app/routes/orders.py
app/static/javascript/scripts.js
app/static/main.css
app/templates/order_info/order_info.html
app/templates/order_info/order_info_create.html
app/templates/order_info/order_info_edit.html
app/templates/order_info/order_info_main.html
app/templates/right_window/profile_info.html

* Get JS row add/remove working and basic form.
* add comment
* create way for route to get lists of order data
* fix remove table row func
* Convert form section to table. Add dropdowns
* change input names
* fix saving to DB
* add default ID
* fix dictionary access
* add join query
* add divs, style and class
* create classes
* made lots of fixes, we have LOTS TODO: The names rendered should be customer.company_id.name OR customer.user_id.name.  We are currently sending usernames and user ID as parameters, but this is causing SQL errors because we are trying to update the database with user ID in lieu of customerID.
* import datetime add conditional date assignment
* add templates to display orders
* Fix name querying and rendering
* remove whitespace
* fix keys
* uncomment route …

337 feature order editor james (#350)

---

app/routes/__init__.py
app/routes/message.py
app/templates/message/message.html

In the box chat, there is no data so I just created the two sampled messages and users to see how the messages are visualized.

Build new message ui for this app
